export { default as HomeLayout } from './HomeLayout';
export { default as Register } from './Register';
export { default as Login } from './Login';
export { default as Landing } from './Landing';
export { default as Error } from './Error';
export { default as Products } from './Products';
export { default as Services } from './Services';
export { default as Solutions } from './Solutions';
export { default as Resources } from './Resources';
export { default as AboutUs } from './AboutUs';
export { default as ContactUs } from './ContactUs';
export { default as Privacy } from './Privacy';
export { default as Terms } from './Terms';
export { default as AdminLogin } from './AdminLogin';
export { default as AdminDashboard, loader as adminDashboardLoader } from './AdminDashboard';
